export const templeSeedData = [
    {
        name: "Pashupatinath Temple",
        type: "temple",
        intro: "One of the most sacred Hindu temples of Nepal, located on the banks of the Bagmati River.",
        myth: "Legend says that Shiva and Parvati took the form of antelopes and sported in the forest here.",
        geoLocation: "27.7104, 85.3487",
        slug: "pashupatinath-temple",
    },
    {
        name: "Swoyambhunath Stupa",
        type: "temple",
        intro: "An ancient religious complex atop a hill in the Kathmandu Valley, often called the Monkey Temple.",
        myth: "It is believed to have self-arisen from a primordial lotus lake that covered the valley.",
        geoLocation: "27.7149, 85.2904",
        slug: "swoyambhunath-stupa",
    },
    {
        name: "Boudhanath Stupa",
        type: "temple",
        intro: "One of the largest spherical stupas in Nepal and the holiest Tibetan Buddhist temple outside Tibet.",
        myth: "Legend tells of a widow who built the stupa with the help of her four sons.",
        geoLocation: "27.7215, 85.3620",
        slug: "boudhanath-stupa",
    },
    {
        name: "Changunarayan Temple",
        type: "temple",
        intro: "The oldest operational Hindu temple in the Kathmandu Valley, dedicated to Lord Vishnu.",
        myth: "Associated with the legend of a Brahmin and a cowherd who discovered Vishnu here.",
        geoLocation: "27.7013, 85.4312",
        slug: "changunarayan-temple",
    },
    {
        name: "Krishna Mandir",
        type: "temple",
        intro: "A masterpiece of stone architecture in Patan Durbar Square, dedicated to Lord Krishna.",
        myth: "Built by King Siddhinarsingh Malla after he saw Krishna and Radha in a dream.",
        geoLocation: "27.6743, 85.3249",
        slug: "krishna-mandir",
    },
    {
        name: "Nyatapola Temple",
        type: "temple",
        intro: "A five-tiered pagoda located in Bhaktapur, dedicated to the goddess Siddhi Lakshmi.",
        myth: "Built to calm the ferocious Bhairava, it is guarded by legendary wrestlers and animals.",
        geoLocation: "27.6713, 85.4293",
        slug: "nyatapola-temple",
    },
];
